disabled_rules:
- line_length
- trailing_whitespace
- identifier_name
- xctfail_message
- unused_optional_binding
included:
excluded:
- Pods
- OpenMarket/AppDelegate.swift
- OpenMarket/SceneDelegate.swift
