disabled_rules:
- line_length
- trailing_whitespace
- identifier_name
- xctfail_message
- unused_optional_binding
- for_where
- weak_delegate
included:
excluded:
- Pods
- OpenMarket/AppDelegate.swift
- OpenMarket/SceneDelegate.swift
